rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode

script: "bundle exec rake test"

env: TEST=true

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby-18mode
    - rvm: jruby-19mode